apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"jenkins","namespace":"devops-tools"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jenkins"}},"template":{"metadata":{"labels":{"app":"jenkins"}},"spec":{"containers":[{"image":"jenkins/jenkins:latest","name":"jenkins","ports":[{"containerPort":8080,"name":"httpport"},{"containerPort":50000,"name":"jnlpport"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/login","port":8080},"initialDelaySeconds":60,"periodSeconds":10,"timeoutSeconds":5},"volumeMounts":[{"mountPath":"/var/jenkins_home","name":"jenkins-home"},{"mountPath":"/root/.m2/repository","name":"mvn-pv-volume"}]}],"securityContext":{"fsGroup":1000,"runAsUser":1000},"volumes":[{"name":"jenkins-home","persistentVolumeClaim":{"claimName":"jenkins-pv-claim"}},{"name":"mvn-pv-volume","persistentVolumeClaim":{"claimName":"mvn-pv-claim"}}]}}}}
    creationTimestamp: "2023-02-14T05:09:38Z"
    generation: 1
    name: jenkins
    namespace: devops-tools
    resourceVersion: "191375"
    uid: 2cb95b7e-0164-4da5-a7bf-6f4fd35518fa
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: jenkins
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: jenkins
      spec:
        containers:
        - image: jenkins/jenkins:latest
          imagePullPolicy: Always
          name: jenkins
          ports:
          - containerPort: 8080
            name: httpport
            protocol: TCP
          - containerPort: 50000
            name: jnlpport
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
          - mountPath: /root/.m2/repository
            name: mvn-pv-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
        - name: mvn-pv-volume
          persistentVolumeClaim:
            claimName: mvn-pv-claim
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-02-14T05:09:38Z"
      lastUpdateTime: "2023-02-14T05:10:50Z"
      message: ReplicaSet "jenkins-566c678d7b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2023-02-21T03:54:24Z"
      lastUpdateTime: "2023-02-21T03:54:24Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
