apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: 'jenkins/jenkins:latest'
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-pv-volume
          mountPath: /var/jenkins_home
        - name: mvn-pv-volume
          mountPath: /root/.m2/repository
      volumes:
      - name: jenkins-pv-volume
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
      - name: mvn-pv-volume
        persistentVolumeClaim:
          claimName: mvn-pv-claim
