apiVersion: v1
kind: PersistentVolume
metadata:
  name: mvn-pv-volume
  labels:
    type: local
spec:
  storageClassName: hostPath
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mvn-pv-claim
spec:
  storageClassName: hostPath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
