pipeline {
     agent any
     triggers {
          pollSCM('* * * * *')
     }
     stages {
          stage("Compile") {
               steps {
                    sh '''
                    cd week6-exercise
                    chmod +x ./gradlew
                    ./gradlew compileJava
                    '''
               }
          }
          stage("Unit test") {
               steps {
                    sh '''
                    cd week6-exercise
                    ./gradlew test
                    '''
               }
          }
          stage("Code coverage") {
               steps {
                    sh 'printenv'
                    echo "My CC branch is: ${env.BRANCH_NAME}"
                    if (env.BRANCH_NAME == "feature-week6") {
                              sh "echo Running code coverage only in the ${env.BRANCH_NAME} branch"
                              sh 'cd week6-exercise'
                              sh 'chmod +x ./gradlew'
                              sh './gradlew jacocoTestReport'
                              sh './gradlew jacocoTestCoverageVerification'
                    }
               }
          }
          stage("Static code analysis") {
               steps {
                    sh '''
                    cd week6-exercise
                    chmod +x ./gradlew
                    ./gradlew checkstyleMain
                    '''
               }
          }
          stage("Package") {
               steps {
                    sh '''
                    cd week6-exercise
                    chmod +x ./gradlew
                    ./gradlew build                    
                    '''
               }
          }
     }
}